import "../styles/globals.css";

export const metadata = {
  title: "Nextjs Multitenant - Starter Kit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
